// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWDw1GcHRscHszWYtcqwgwDUT86tkstPg',
    appId: '1:639911212248:web:bf6c7c5b4a70fd259bd3ad',
    messagingSenderId: '639911212248',
    projectId: 'cointrail-expense-tracker',
    authDomain: 'cointrail-expense-tracker.firebaseapp.com',
    storageBucket: 'cointrail-expense-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB09BKnTggSPrt60A9yzXs8Vcc7uPDMCfI',
    appId: '1:639911212248:android:072220d0158041a79bd3ad',
    messagingSenderId: '639911212248',
    projectId: 'cointrail-expense-tracker',
    storageBucket: 'cointrail-expense-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4xSj4BUtVFwneR38j27CigQdE41dNGj8',
    appId: '1:639911212248:ios:419f3538b759fa719bd3ad',
    messagingSenderId: '639911212248',
    projectId: 'cointrail-expense-tracker',
    storageBucket: 'cointrail-expense-tracker.firebasestorage.app',
    androidClientId: '639911212248-5f7vqc3188a4cejor77qbu5p0qfcm8m1.apps.googleusercontent.com',
    iosClientId: '639911212248-d19vqa73gc08iblofk88o87pk85nv7eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cointrail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4xSj4BUtVFwneR38j27CigQdE41dNGj8',
    appId: '1:639911212248:ios:419f3538b759fa719bd3ad',
    messagingSenderId: '639911212248',
    projectId: 'cointrail-expense-tracker',
    storageBucket: 'cointrail-expense-tracker.firebasestorage.app',
    androidClientId: '639911212248-5f7vqc3188a4cejor77qbu5p0qfcm8m1.apps.googleusercontent.com',
    iosClientId: '639911212248-d19vqa73gc08iblofk88o87pk85nv7eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cointrail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWDw1GcHRscHszWYtcqwgwDUT86tkstPg',
    appId: '1:639911212248:web:5af16cb51221a6129bd3ad',
    messagingSenderId: '639911212248',
    projectId: 'cointrail-expense-tracker',
    authDomain: 'cointrail-expense-tracker.firebaseapp.com',
    storageBucket: 'cointrail-expense-tracker.firebasestorage.app',
  );

}